package com.shiver.chestcavity.registry;

import com.shiver.chestcavity.score.ScoreRef;

public final class CCOrganScores {

    public static final String HEALTH = "health";
    public static final String LUCK = "luck";
    public static final String STRENGTH = "strength";
    public static final String SPEED = "speed";
    public static final String DEFENSE = "defense";
    public static final String NERVES = "nerves";
    public static final String MINING_SPEED = "mining_speed";
    public static final String EASE_OF_ACCESS = "ease_of_access";
    public static final String INCOMPATIBILITY = "incompatibility";
    public static final String DIGESTION = "digestion";
    public static final String NUTRITION = "nutrition";
    public static final String FILTRATION = "filtration";
    public static final String DETOXIFICATION = "detoxification";
    public static final String METABOLISM = "metabolism";
    public static final String ENDURANCE = "endurance";
    public static final String FURNACE_POWERED = "furnace_powered";
    public static final String GRAZING = "grazing";
    public static final String IRON_REPAIR = "iron_repair";
    public static final String BREATH = "breath";
    public static final String BREATH_CAPACITY = "breath_capacity";
    public static final String WATER_BREATH = "water_breath";
    public static final String BUOYANT = "buoyant";
    public static final String CREEPY = "creepy";
    public static final String EXPLOSIVE = "explosive";
    public static final String FIRE_RESISTANT = "fire_resistant";
    public static final String HYDROALLERGENIC = "hydroallergenic";
    public static final String HYDROPHOBIA = "hydrophobia";
    public static final String IMPACT_RESISTANT = "impact_resistant";
    public static final String KNOCKBACK_RESISTANT = "knockback_resistant";
    public static final String LEAPING = "leaping";
    public static final String LIGHTWEIGHT = "lightweight";
    public static final String SWIM_SPEED = "swim_speed";
    public static final String GLOWING = "glowing";
    public static final String PYROMANCY = "pyromancy";
    public static final String LAUNCHING = "launching";
    public static final String VENOMOUS = "venomous";
    public static final String ARROW_DODGING = "arrow_dodging";
    public static final String BUFF_PURGING = "buff_purging";
    public static final String WITHERED = "withered";
    public static final String DRAGON_BOMBS = "dragon_bombs";
    public static final String FORCEFUL_SPIT = "forceful_spit";
    public static final String GHASTLY = "ghastly";
    public static final String SHULKER_BULLETS = "shulker_bullets";
    public static final String SILK = "silk";
    public static final String CRYSTALSYNTHESIS = "crystalsynthesis";
    public static final String PHOTOSYNTHESIS = "photosynthesis";
    public static final String DESTRUCTIVE_COLLISIONS = "destructive_collisions";

    public static final ScoreRef HEALTH_REF = ScoreRef.of(HEALTH);
    public static final ScoreRef LUCK_REF = ScoreRef.of(LUCK);
    public static final ScoreRef STRENGTH_REF = ScoreRef.of(STRENGTH);
    public static final ScoreRef SPEED_REF = ScoreRef.of(SPEED);
    public static final ScoreRef DEFENSE_REF = ScoreRef.of(DEFENSE);
    public static final ScoreRef NERVES_REF = ScoreRef.of(NERVES);
    public static final ScoreRef MINING_SPEED_REF = ScoreRef.of(MINING_SPEED);
    public static final ScoreRef EASE_OF_ACCESS_REF = ScoreRef.of(EASE_OF_ACCESS);
    public static final ScoreRef INCOMPATIBILITY_REF = ScoreRef.of(INCOMPATIBILITY);
    public static final ScoreRef DIGESTION_REF = ScoreRef.of(DIGESTION);
    public static final ScoreRef NUTRITION_REF = ScoreRef.of(NUTRITION);
    public static final ScoreRef FILTRATION_REF = ScoreRef.of(FILTRATION);
    public static final ScoreRef DETOXIFICATION_REF = ScoreRef.of(DETOXIFICATION);
    public static final ScoreRef METABOLISM_REF = ScoreRef.of(METABOLISM);
    public static final ScoreRef ENDURANCE_REF = ScoreRef.of(ENDURANCE);
    public static final ScoreRef FURNACE_POWERED_REF = ScoreRef.of(FURNACE_POWERED);
    public static final ScoreRef GRAZING_REF = ScoreRef.of(GRAZING);
    public static final ScoreRef IRON_REPAIR_REF = ScoreRef.of(IRON_REPAIR);
    public static final ScoreRef BREATH_REF = ScoreRef.of(BREATH);
    public static final ScoreRef BREATH_CAPACITY_REF = ScoreRef.of(BREATH_CAPACITY);
    public static final ScoreRef WATER_BREATH_REF = ScoreRef.of(WATER_BREATH);
    public static final ScoreRef BUOYANT_REF = ScoreRef.of(BUOYANT);
    public static final ScoreRef CREEPY_REF = ScoreRef.of(CREEPY);
    public static final ScoreRef EXPLOSIVE_REF = ScoreRef.of(EXPLOSIVE);
    public static final ScoreRef FIRE_RESISTANT_REF = ScoreRef.of(FIRE_RESISTANT);
    public static final ScoreRef HYDROALLERGENIC_REF = ScoreRef.of(HYDROALLERGENIC);
    public static final ScoreRef HYDROPHOBIA_REF = ScoreRef.of(HYDROPHOBIA);
    public static final ScoreRef IMPACT_RESISTANT_REF = ScoreRef.of(IMPACT_RESISTANT);
    public static final ScoreRef KNOCKBACK_RESISTANT_REF = ScoreRef.of(KNOCKBACK_RESISTANT);
    public static final ScoreRef LEAPING_REF = ScoreRef.of(LEAPING);
    public static final ScoreRef LIGHTWEIGHT_REF = ScoreRef.of(LIGHTWEIGHT);
    public static final ScoreRef SWIM_SPEED_REF = ScoreRef.of(SWIM_SPEED);
    public static final ScoreRef GLOWING_REF = ScoreRef.of(GLOWING);
    public static final ScoreRef PYROMANCY_REF = ScoreRef.of(PYROMANCY);
    public static final ScoreRef LAUNCHING_REF = ScoreRef.of(LAUNCHING);
    public static final ScoreRef VENOMOUS_REF = ScoreRef.of(VENOMOUS);
    public static final ScoreRef ARROW_DODGING_REF = ScoreRef.of(ARROW_DODGING);
    public static final ScoreRef BUFF_PURGING_REF = ScoreRef.of(BUFF_PURGING);
    public static final ScoreRef WITHERED_REF = ScoreRef.of(WITHERED);
    public static final ScoreRef DRAGON_BOMBS_REF = ScoreRef.of(DRAGON_BOMBS);
    public static final ScoreRef FORCEFUL_SPIT_REF = ScoreRef.of(FORCEFUL_SPIT);
    public static final ScoreRef GHASTLY_REF = ScoreRef.of(GHASTLY);
    public static final ScoreRef SHULKER_BULLETS_REF = ScoreRef.of(SHULKER_BULLETS);
    public static final ScoreRef SILK_REF = ScoreRef.of(SILK);
    public static final ScoreRef CRYSTALSYNTHESIS_REF = ScoreRef.of(CRYSTALSYNTHESIS);
    public static final ScoreRef PHOTOSYNTHESIS_REF = ScoreRef.of(PHOTOSYNTHESIS);
    public static final ScoreRef DESTRUCTIVE_COLLISIONS_REF = ScoreRef.of(DESTRUCTIVE_COLLISIONS);

    private CCOrganScores() {
    }
}
